jsSrcDir: src/js/
jsConcatDir: dist/js/
cssSrcDir: src/css/
cssDistDir: dist/css/

viewsJsSrcDir: viewsSrc/views/js/
viewsJsConcatDir: viewsDist/views/js/
viewsCssSrcDir: viewsSrc/views/css/
viewsCssDistDir: viewsDist/views/css/