jsSrcDir: src/js/
jsConcatDir: dist/js/
cssSrcDir: src/css/
cssDistDir: dist/css/

viewsJsSrcDir: src/views/js/
viewsJsConcatDir: dist/views/js/
viewsCssSrcDir: src/views/css/
viewsCssDistDir: dist/views/css/